### ISSUE TITLE
How to intsall this on the esp8226 mini d1?

### ISSUE THREAD

**Issue by userix** [nikzin96/modified_HollowClock4#6]
Sorry, I'm a noob here.  how do I install this firmware to the 8226 d1 mini?  Thanks

I get this error
"
Z:\3D Prints\Hollow_Clock_4_5636482\modified_HollowClock4-main\firmware\firmware.ino:26:10: fatal error: ESP8266WiFi.h: No such file or directory
 #include <ESP8266WiFi.h>
          ^~~~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: ESP8266WiFi.h: No such file or directory"

**Comment by HennieLP** [comment]
did you select the ESP8266 In the Arduino IDE ?

**Comment by HennieLP** [comment]
Hm that’s weird because the library is normally automatically installed if you can select the ESP8266

**Comment by userix** [comment]
Actually it did work!  I had to select the d1 mini wemos lolin board for it to work. I think the board I bought is the smaller d1 mini

**Comment by HennieLP** [comment]
Resolved
